application: yourappname
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /QueueAMasterTask
  script: urlhandlers.QueueAMasterTask.app
  secure: always

- url: /_ah/queue/masterTaskQ
  script: urlhandlers.HandlerForMasterTaskQ.app
  secure: always

- url: /_ah/queue/googleTaskQ
  script: urlhandlers.HandlerForGoogleTaskQ.app
  secure: always

- url: /_ah/queue/appleTaskQ
  script: urlhandlers.HandlerForAppleTaskQ.app
  secure: always

- url: /_ah/queue/windowsTaskQ
  script: urlhandlers.HandlerForWindowsTaskQ.app
  secure: always

- url: /.*
  script: server.app
  secure: always

libraries:
- name: lxml
  version: "2.3"
- name: pycrypto
  version: "latest"